# Generated by Django 3.1.2 on 2021-11-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211125_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='img',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='make',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
