# Generated by Django 3.1.2 on 2021-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211126_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
