# Generated by Django 3.1.2 on 2021-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211127_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part',
        ),
        migrations.AddField(
            model_name='part',
            name='records',
            field=models.ManyToManyField(to='main_app.Record'),
        ),
    ]
