# Generated by Django 3.1.2 on 2021-11-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20211127_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='records',
        ),
        migrations.AddField(
            model_name='record',
            name='parts',
            field=models.ManyToManyField(to='main_app.Part'),
        ),
    ]
