# Generated by Django 3.1.2 on 2021-11-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_auto_20211127_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='record',
            name='tech',
            field=models.ForeignKey(default='No Technician Assigned', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
