# Generated by Django 3.1.2 on 2021-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211129_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
